services:
  mahjong-app:
    image: mdskwong/mahjong:3b052188dd947865859badeb0858822755a7f61a
    restart: unless-stopped
    ports:
      - "80:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    working_dir: /app
    deploy:
      resources:
        limits:
          memory: 1G
    platform: linux/arm64