services:
  mahjong-app:
    image: mdskwong/mahjong:2e2fde04f63a31b3a7c8f8deb2e7cb6847b83d98
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    working_dir: /app
    deploy:
      resources:
        limits:
          memory: 1G
    platform: linux/arm64